"""set nullable true on General foreignkey

Revision ID: fcb92a1625d7
Revises: a3fb5ebbf9e0
Create Date: 2023-04-04 18:42:20.497311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb92a1625d7'
down_revision = 'a3fb5ebbf9e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('general', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('general', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.create_foreign_key(None, 'general', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'general', 'subcategory', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'general', 'category', ['category_id'], ['id'])
    op.drop_column('general', 'category')
    op.drop_column('general', 'user')
    op.drop_column('general', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('subcategory', sa.INTEGER(), nullable=False))
    op.add_column('general', sa.Column('user', sa.INTEGER(), nullable=False))
    op.add_column('general', sa.Column('category', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.drop_constraint(None, 'general', type_='foreignkey')
    op.create_foreign_key(None, 'general', 'subcategory', ['subcategory'], ['id'])
    op.create_foreign_key(None, 'general', 'category', ['category'], ['id'])
    op.create_foreign_key(None, 'general', 'user', ['user'], ['id'])
    op.drop_column('general', 'subcategory_id')
    op.drop_column('general', 'category_id')
    op.drop_column('general', 'user_id')
    # ### end Alembic commands ###
